# Generated by Django 4.2.11 on 2025-01-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidacionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('email', models.CharField(max_length=254)),
                ('fecha_alta', models.DateField(null=True)),
                ('fecha_uso', models.DateField(null=True)),
            ],
        ),
    ]
