# Generated by Django 4.2.11 on 2024-04-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Beca", new_name="Becas",),
    ]
