# Generated by Django 4.2.11 on 2024-04-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_rename_beca_becas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='socio',
        ),
        migrations.AddField(
            model_name='socios',
            name='personas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.personas'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.categorias')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.personas')),
            ],
        ),
    ]
