# Generated by Django 4.2.11 on 2024-04-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_remove_personas_socio_socios_personas_jugadores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JugadoresCategoria',
        ),
    ]
