# Generated by Django 4.2.11 on 2024-05-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0005_personas_direccion_personas_telefono"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="personas",
            constraint=models.UniqueConstraint(
                fields=("nombre", "apellido"), name="unique_nombre_apellido"
            ),
        ),
    ]
