# Generated by Django 4.2.11 on 2024-05-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0006_personas_unique_nombre_apellido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personas",
            name="fecha_nacimiento",
            field=models.DateField(null=True),
        ),
    ]
