# Generated by Django 4.2.11 on 2024-05-12 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0011_cuota_socios_fecha_alta_socios_fecha_baja'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuota',
            new_name='Cuotas',
        ),
    ]
