# Generated by Django 4.2.11 on 2024-05-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0012_rename_cuota_cuotas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cuotas", old_name="cant_hermanos", new_name="cant_int",
        ),
    ]
