# Generated by Django 4.2.11 on 2024-05-21 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0013_rename_cant_hermanos_cuotas_cant_int"),
    ]

    operations = [
        migrations.CreateModel(
            name="BecasJugador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.CharField(max_length=4)),
                (
                    "beca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuracion.becas",
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuracion.jugadores",
                    ),
                ),
            ],
        ),
    ]
