# Generated by Django 4.2.11 on 2024-05-21 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0014_becasjugador"),
    ]

    operations = [
        migrations.CreateModel(
            name="BecasMotivos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concepto", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CalidadIntegrante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concepto", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="becasjugador",
            name="mesDesde",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ENE", "Enero"),
                    ("FEB", "Febrero"),
                    ("MAR", "Marzo"),
                    ("ABR", "Abril"),
                    ("MAY", "Mayo"),
                    ("JUN", "Junio"),
                    ("JUL", "Julio"),
                    ("AGO", "Agosto"),
                    ("SEP", "Septiembre"),
                    ("OCT", "Octubre"),
                    ("NOV", "Noviembre"),
                    ("DIC", "Diciembre"),
                ],
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="becasjugador",
            name="mesHasta",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ENE", "Enero"),
                    ("FEB", "Febrero"),
                    ("MAR", "Marzo"),
                    ("ABR", "Abril"),
                    ("MAY", "Mayo"),
                    ("JUN", "Junio"),
                    ("JUL", "Julio"),
                    ("AGO", "Agosto"),
                    ("SEP", "Septiembre"),
                    ("OCT", "Octubre"),
                    ("NOV", "Noviembre"),
                    ("DIC", "Diciembre"),
                ],
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="IntegrantesClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_desde", models.DateField(null=True)),
                ("fecha_hasta", models.DateField(null=True)),
                (
                    "calidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuracion.calidadintegrante",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuracion.personas",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="becasjugador",
            name="motivoSolicitud",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="configuracion.becasmotivos",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="becasjugador",
            name="solicita",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="configuracion.integrantesclub",
            ),
            preserve_default=False,
        ),
    ]
