# Generated by Django 4.2.11 on 2024-07-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0016_alter_becasjugador_motivosolicitud"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorias",
            name="paga_disciplina",
            field=models.BooleanField(default="True"),
        ),
        migrations.AddField(
            model_name="jugadores",
            name="fecha_desde",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="jugadores",
            name="fecha_hasta",
            field=models.DateField(null=True),
        ),
    ]
