# Generated by Django 4.2.11 on 2024-07-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0017_categorias_paga_disciplina_jugadores_fecha_desde_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jugadores',
            constraint=models.UniqueConstraint(fields=('persona', 'categoria', 'fecha_desde', 'fecha_hasta'), name='unique_player_category_period'),
        ),
    ]
