# Generated by Django 4.2.11 on 2024-08-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "configuracion",
            "0017_categorias_paga_disciplina_jugadores_fecha_desde_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cuotas", name="fecha_alta", field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="cuotas", name="fecha_baja", field=models.DateField(null=True),
        ),
    ]
