# Generated by Django 4.2.11 on 2024-07-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0018_jugadores_unique_player_category_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
