# Generated by Django 4.2.11 on 2024-08-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0018_cuotas_fecha_alta_cuotas_fecha_baja"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cuotas", old_name="fecha_alta", new_name="fecha_desde",
        ),
        migrations.RenameField(
            model_name="cuotas", old_name="fecha_baja", new_name="fecha_hasta",
        ),
    ]
