# Generated by Django 4.2.11 on 2024-07-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0019_jugadores_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
