# Generated by Django 4.2.11 on 2024-08-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0019_rename_fecha_alta_cuotas_fecha_desde_and_more'),
        ('configuracion', '0021_remove_jugadores_unique_player_category_period_and_more'),
    ]

    operations = [
    ]
