# Generated by Django 4.2.11 on 2024-08-13 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0019_rename_fecha_alta_cuotas_fecha_desde_and_more'),
        ('configuracion', '0022_disciplinas_activo'),
    ]

    operations = [
    ]
