# Generated by Django 4.2.11 on 2024-08-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0023_merge_20240812_2316"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disciplinas",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
