# Generated by Django 4.2.11 on 2024-08-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0022_merge_20240805_1532'),
        ('configuracion', '0023_merge_20240812_2316'),
    ]

    operations = [
    ]
