# Generated by Django 4.2.11 on 2024-08-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0024_alter_disciplinas_nombre"),
        ("configuracion", "0024_merge_20240817_0845"),
    ]

    operations = []
