# Generated by Django 4.2.11 on 2024-09-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0025_merge_20240828_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='becas',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='becas',
            name='fecha_desde',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='becas',
            name='fecha_hasta',
            field=models.DateField(null=True),
        ),
    ]
