# Generated by Django 4.2.11 on 2025-01-30 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracion', '0025_merge_20240828_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrantesclub',
            name='persona',
        ),
        migrations.AddField(
            model_name='integrantesclub',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
