# Generated by Django 4.2.11 on 2025-02-03 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0027_alter_integrantesclub_fecha_hasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDeportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProfesoresDeportivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField(null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.categorias')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.integrantesclub')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('asiste', models.CharField(blank=True, choices=[('S', 'SI'), ('N', 'NO')], default='N', max_length=1)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.eventodeportivo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.jugadores')),
            ],
        ),
    ]
