# Generated by Django 4.2.11 on 2025-02-11 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0028_eventodeportivo_profesoresdeportivos_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrantesClubCategorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField(null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.categorias')),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.integrantesclub')),
            ],
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
