# Generated by Django 4.2.11 on 2025-03-10 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0030_caracteristicaevaluar'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicaevaluar',
            name='caracteristicaPadre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.caracteristicaevaluar'),
        ),
    ]
