# Generated by Django 4.2.11 on 2025-03-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0031_caracteristicaevaluar_caracteristicapadre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicaevaluar',
            name='caracteristicaPadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.caracteristicaevaluar'),
        ),
    ]
