# Generated by Django 4.2.11 on 2024-04-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cobros", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="jugadorescategoria", name="categoria",),
        migrations.RemoveField(model_name="jugadorescategoria", name="persona",),
        migrations.RemoveField(model_name="personas", name="socio",),
        migrations.DeleteModel(name="Categorias",),
        migrations.DeleteModel(name="Disciplinas",),
        migrations.DeleteModel(name="JugadoresCategoria",),
        migrations.DeleteModel(name="Personas",),
        migrations.DeleteModel(name="Socios",),
    ]
