# Generated by Django 4.2.11 on 2024-05-07 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configuracion", "0005_personas_direccion_personas_telefono"),
        ("cobros", "0002_remove_jugadorescategoria_categoria_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cobros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_cobro", models.DateField()),
                ("monto", models.FloatField()),
                (
                    "socio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuracion.socios",
                    ),
                ),
            ],
        ),
    ]
