# Generated by Django 4.2.11 on 2024-05-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cobros',
        ),
    ]
