# Generated by Django 4.2.11 on 2024-07-04 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "configuracion",
            "0017_categorias_paga_disciplina_jugadores_fecha_desde_and_more",
        ),
        ("cobros", "0005_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SituacionInicial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.IntegerField()),
                ("mes", models.IntegerField()),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuracion.disciplinas",
                    ),
                ),
            ],
        ),
    ]
