# Generated by Django 4.2.11 on 2025-01-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
