# Generated by Django 4.2.11 on 2025-01-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0004_menugroups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuGroups',
            new_name='MenuGroup',
        ),
    ]
