# Generated by Django 4.2.11 on 2025-02-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_menugroups_menugroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='nivel',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
