# Generated by Django 4.2.11 on 2025-03-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestJugadores', '0003_remove_evaltecnicotacticaactitudinaljugador_tipoevaluacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaltecnicotacticaactitudinal',
            name='fechaFin',
            field=models.DateField(default="2025-02-15"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaltecnicotacticaactitudinal',
            name='fechaInicio',
            field=models.DateField(default="2025-03-15"),
            preserve_default=False,
        ),
    ]
