# Generated by Django 4.2.11 on 2025-03-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestJugadores', '0004_evaltecnicotacticaactitudinal_fechafin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaltecnicotacticaactitudinalcaracteristica',
            old_name='carteristicaEvaluar',
            new_name='carateristicaEvaluar',
        ),
    ]
