# Generated by Django 4.2.11 on 2025-03-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestJugadores', '0005_rename_carteristicaevaluar_evaltecnicotacticaactitudinalcaracteristica_carateristicaevaluar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaltecnicotacticaactitudinaljugador',
            old_name='carteristicaEvaluar',
            new_name='caracteristicaEvaluar',
        ),
    ]
