# Generated by Django 4.2.11 on 2025-03-11 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0032_alter_caracteristicaevaluar_caracteristicapadre'),
        ('gestJugadores', '0006_rename_carteristicaevaluar_evaltecnicotacticaactitudinaljugador_caracteristicaevaluar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaltecnicotacticaactitudinaljugador',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.integrantesclubcategorias'),
        ),
    ]
